--유저
ALTER TABLE TRAVIEW.USER ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE TRAVIEW.`USER` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--유저권한
ALTER TABLE TRAVIEW.ROLE_INFO ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE TRAVIEW.`ROLE_INFO` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--게시판
ALTER TABLE TRAVIEW.POST ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE TRAVIEW.`POST` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--게시판 분류
ALTER TABLE TRAVIEW.POST_INFO ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE TRAVIEW.`POST_INFO` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--댓글
ALTER TABLE TRAVIEW.COMMENT ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE TRAVIEW.`COMMENT` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;



