--유저
ALTER TABLE USER ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE `USER` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--유저권한
ALTER TABLE ROLE_INFO ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE `ROLE_INFO` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--게시판
ALTER TABLE POST ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE `POST` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--게시판 분류
ALTER TABLE POST_INFO ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE `POST_INFO` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;
--댓글
ALTER TABLE COMMENT ADD USE_YN VARCHAR(1) NULL;
ALTER TABLE `COMMENT` MODIFY COLUMN USE_YN VARCHAR(1) DEFAULT 'Y'  NOT NULL;



